version: "3.2"
services:
    app:
      build:
        context: ./
        dockerfile: src/main/docker/Dockerfile.jvm
      ports:
        - 8888:8888
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
      networks:
        - elk
      depends_on:
        - mongodb_container

    mongodb_container:
      image: mongo:latest
      container_name: elk_mongodb
      restart: always
      ports:
        - 27019:27017
      environment:
        - MONGO_INITDB_ROOT_USERNAME=admin
        - MONGO_INITDB_ROOT_PASSWORD=admin
      networks:
        - elk
      volumes:
        -  mongodb_data:/data/db

    elasticsearch:
      image: docker.io/elastic/elasticsearch:7.16.3
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        discovery.type: "single-node"
#        xpack.security.enabled: "true"  # 禁用 X-Pack 安全性功能
#        xpack.security.http.ssl.enabled: "true"  # 禁用 HTTPS
#        xpack.security.transport.ssl.enabled: "true"  # 禁用 HTTPS
#        cluster.routing.allocation.disk.threshold_enabled: false
#        ELASTIC_PASSWORD: Aa00000000
      restart: always
      volumes:
        - ./elastic_data:/usr/share/elasticsearch/data/
      networks:
        - elk

    logstash:
      image: docker.io/elastic/logstash:7.16.3
      volumes:
        - ./gelf.conf:/usr/share/logstash/pipeline/gelf.conf
      ports:
        - "12201:12201/udp"
        - "5000:5000"
        - "9600:9600"
      networks:
        - elk
      depends_on:
        - elasticsearch

    kibana:
      image: docker.io/elastic/kibana:7.16.3
      restart: always
      ports:
        - "5601:5601"
      networks:
        - elk
      depends_on:
        - elasticsearch
      volumes:
        - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
    elk:
      driver: bridge
volumes:
    mongodb_data: {}
    elastic_data: {}
