version: "3.7"
services:
    setup:
      profiles:
        - setup
      build:
        context: setup/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      init: true
      volumes:
        - ./setup/entrypoint.sh:/entrypoint.sh:ro
        - ./setup/lib.sh:/lib.sh:ro
        - ./setup/roles:/roles:ro
      environment:
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
        LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
        KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      networks:
        - elk
      depends_on:
        - elasticsearch

    elasticsearch:
      build:
        context: elasticsearch/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        node.name: "elasticsearch"
        ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        discovery.type: "single-node"
        ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
        - elasticsearch:/usr/share/elasticsearch/data
      networks:
        - elk
      restart: always

    logstash:
      build:
        context: logstash/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      ports:
        - "12201:12201/udp"
        - "5000:5000"
        - "9600:9600"
      environment:
        LS_JAVA_OPTS: -Xms256m -Xmx256m
        LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      volumes:
        - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
        - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      networks:
        - elk
      depends_on:
        - elasticsearch
      restart: always

    kibana:
      build:
        context: kibana/
        args:
          ELASTIC_VERSION: ${ELASTIC_VERSION}
      ports:
        - "5601:5601"
      environment:
        KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      volumes:
        - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      networks:
        - elk
      depends_on:
        - elasticsearch
      restart: always

networks:
    elk:
      #  需要先手動創建 network
      external: true
volumes:
    elasticsearch: {}
